---
name: pre-commit

description: pre-commit

runs:
  using: composite
  steps:
    - name: pre-commit
      uses: pre-commit/action@v2.0.3
      with:
        extra_args: --all-files --show-diff-on-failure
