---
name: test fail or success

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fail_or_success:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: success
        run: exit 0
      # - name: fail
      #   run: exit 1
